### ISSUE TITLE
is headless cluster an issue?

### ISSUE THREAD

**Issue by Bkamau** [mailgun/kafka-pixy#139]
It happens that i can post to kafka, query topics, and topic configs together with partitions but when i query for offsets, i get this error
{
    "error": "failed to fetch topic configuration: zk: node does not exist"
}

anything am missing?

**Comment by horkhe** [comment]
Apparently you are missing [zookeeper data](https://github.com/mailgun/kafka-pixy/blob/master/default.yaml#L38-L46) in your config or it is not correct.

**Comment by horkhe** [comment]
Feel free to reopen if you have follow up questions.
