### ISSUE TITLE
How to install without docker?

### ISSUE THREAD

**Issue by shaharmor** [mailgun/kafka-pixy#158]
Hi,

We would like to use kafka-pixy as a "sidecar-like" proxy installed along side our app, but we don't use docker, just normal VMs.

Any instructions on how to install kafka-pixy on Linux? (Specifically Ubuntu 16.04)

**Comment by horkhe** [comment]
@shaharmor just grab the latest release form GitHub (e.g. [v0.16.0](https://github.com/mailgun/kafka-pixy/releases/tag/v0.16.0)), unpack and run the executable.

**Comment by shaharmor** [comment]
@horkhe 	Yeah I already saw that, opened the ticket before.
I guess there is no systemd unit for this already. Will have to write my own.

Btw, are there any benchmarks for kafka-pixy? It looks like an awesome piece of software that greatly simplifies Kafka integrations.

Also, thanks for the project :)

**Comment by horkhe** [comment]
Sorry I do not have concrete numbers at hand. But you can easily benchmark it for yourself using `testconsumer` and `testproducer` command line utils created specifically for that purpose. They are packaged in the release. Start them with `--help` to get a list of options. They both connect to kafka-pixy via gRPC.
