### ISSUE TITLE
Getting an error for grpc.ClientConn

### ISSUE THREAD

**Issue by amitgurav04** [mailgun/kafka-pixy#159]
I am trying to run simple go program. I am following the steps given in https://github.com/mailgun/kafka-pixy/blob/master/quick-start-golang.md

On Go version 1.11

But getting following error:

cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/mailgun/kafka-pixy/vendor/google.golang.org/grpc".ClientConn in argument to pb.NewKafkaPixyClient

**Comment by horkhe** [comment]
Looks like you vendored entire `kafka-pixy` repository content along with its own `vendor` folder. Is my assumption correct? The only thing that you need to vendor is `github.com/mailgun/kafka-pixy/gen/golang` package, just remove the rest and you should be fine.

**Comment by amitgurav04** [comment]
Thanks @horkhe . I did as you suggested. It's working now. Can you please update this in document as well. so that no confusion for other users.

**Comment by horkhe** [comment]
I am glad to hear that it worked for you. Although I do not think it is worth of documentation update. Because this is just basic vendoring mechanics.
