### ISSUE TITLE
How to secure the kafka-pixy?

### ISSUE THREAD

**Issue by amitgurav04** [mailgun/kafka-pixy#160]
How can I enable the HTTPS/SSL in kafka-pixy so that the request/response between client and kafka-pixy become secure.

Please suggest if any configurations are available to do the same.

Thanks in advance.

**Comment by horkhe** [comment]
There is no way to do that. We never needed that. But, it should be relatively easy to implement. A gRPC listener should be started with TLS config. And then client would be able to use secure channel. If you want you can suggest a PR.

**Comment by amitgurav04** [comment]
Thanks for giving the way to do this .  I will implement this.

**Comment by maxthomas** [comment]
hey there, i'm very interested in working on this capability. i sketched out a little proposal, would you let me know what you think generally so we can agree on how best to structure things?

i'd propose:

- small section in config, `grpc`, that contains paths to server certificates
- add this to the `config.go` code
- add method in `config.go` capable of producting `grpc.ServerOpt` struct (either insecure, the default, or TLS if detected in config)
- use this method when creating gRPC server throughout the code

what are your thoughts? if it looks good i'll start implementing it like that.

**Comment by horkhe** [comment]
Thank you @maxthomas, your proposal seems reasonable. I would suggested to call the section `tls` though. And if you could make sure that both gRPC and HTTP servers use TLS if configured that would be great.

**Comment by maxthomas** [comment]
thanks @horkhe ! i'll start working on this and push up an MR when it's ready for your review!

**Comment by maxthomas** [comment]
would love feedback on #167 !

**Comment by horkhe** [comment]
Fixed by #167
