### ISSUE TITLE
move to go mod

### ISSUE THREAD

**Issue by maxthomas** [mailgun/kafka-pixy#171]
hey @horkhe , would you and your team have any interest in moving the project to `go mod`? it'd make the project depend upon golang `1.11` or so, but that seems to be the case already in the CI file. let me know what you think!

**Comment by horkhe** [comment]
After they pulled a fast one on us with golang/dep I was hesitant to switch to `go mod` at early stage. But now it seems it is here to stay. I think the time has come to start using it.

**Comment by maxthomas** [comment]
sounds good. would you like the dependencies to still be vendored as well?

**Comment by horkhe** [comment]
Our internal Jenkins job expects them to be vendored, so let's keep them for now.

**Comment by horkhe** [comment]
Implemented in #174
