### ISSUE TITLE
failed to run and build in window

### ISSUE THREAD

**Issue by liuxuisme** [mailgun/kafka-pixy#176]
C:\GoProject\src\github.com\mailgun\kafka-pixy>go run main.go
build github.com/sirupsen/logrus/hooks/syslog: cannot load github.com/sirupsen/logrus/hooks/syslog: no Go source files

**Comment by horkhe** [comment]
Sorry, no idea. We are not using windows. There is probably something wrong with your go installation. Anyways this is something we cannot help with.
