### ISSUE TITLE
Getting issue with docker

### ISSUE THREAD

**Issue by KuldeepGaur** [mailgun/kafka-pixy#188]
It might be the very basic stuff:

Getting this issue 

**Failed to load config: err=(read /etc/kafka-pixy.yaml: is a directory)**

I'm running docker as 

$ docker run -d -p 19091:19091 -p 19092:19092 -v  kafka-pixy.yaml:/etc/kafka-pixy.yaml:rw mailgun/kafka-pixy --config  /etc/kafka-pixy.yaml

I have the kafka-pixy.yaml on my local directory from where I'm running the docker instance.

Thanks

**Comment by LvXinPeng** [comment]
maybe you can try, 
`docker run -d -p 19091:19091 -p 19092:19092 -v kafka-pixy.yaml:/etc/kafka-pixy.yaml:rw mailgun/kafka-pixy --config kafka-pixy.yaml`

**Comment by KuldeepGaur** [comment]
thanks but no luck with this

**Comment by LvXinPeng** [comment]
> thanks but no luck with this
copy kafka-pixy.yml to the folder '/etc/' and try again
`docker run -d -p 19091:19091 -p 19092:19092 -v /etc/kafka-pixy.yaml:/etc/kafka-pixy.yaml:rw mailgun/kafka-pixy --config /etc/kafka-pixy.yaml`

**Comment by KuldeepGaur** [comment]
> > copy kafka-pixy.yml to the folder '/etc/' and try again
> > `docker run -d -p 19091:19091 -p 19092:19092 -v /etc/kafka-pixy.yaml:/etc/kafka-pixy.yaml:rw mailgun/kafka-pixy --config /etc/kafka-pixy.yaml`

Thanks but Still not working.
getting below issue 
 
**Failed to load config: err=(read /etc/kafka-pixy.yaml: is a directory)**

**Comment by KuldeepGaur** [comment]
@LvXinPeng the issue is coming on windows machine with windows docker toolbox.

On Linux machine same is working fine
