### ISSUE TITLE
Passing config

### ISSUE THREAD

**Issue by ruslanruslanruslan** [mailgun/kafka-pixy#189]
Hi!
I've tried to use --config /etc/kafka-pixy.yaml and million of other ways but get "Failed to load config: err=(open /etc/kafka-pixy.yaml: no such file or directory)" anyway.
What folder I have to mount to compose to pass config file? Also I'm changing /etc/default.yaml and /etc/kafka-pixy.yaml in the docker but nothing happen

**Comment by horkhe** [comment]
You can mount it anywhere you want, the important thing is to have `--config <filename>` point to the location of the file inside the container.
