### ISSUE TITLE
More detail on use-cases in relation to microservices

### ISSUE THREAD

**Issue by Analect** [mailgun/kafka-pixy#53]
@horkhe 
Thanks for this interesting project.
I saw your explanation for the need that kafka-pixy is fulfilling here:
https://groups.google.com/forum/#!topic/kafka-clients/ZEkcwETZa0A

I'm not sure if you are using any framework for micro-services, but we're considering [seneca](senecajs.org) that has a working interface to kafka ... https://www.npmjs.com/package/seneca-kafka-transport ... a version of which we currently use, but it's obviously not leveraging some of the benefits that something like kafka-pixy brings.

Would it be possible to continue a conversation off-line to understand a little more beyond your explanation in the kafka-user forum?

Thanks,
Colum

**Comment by horkhe** [comment]
Hey Colum, thank you for your interest in the project. Please feel free to ask further questions, I will be glad to answer.

As for micro-service frameworks, we do not use any. Our services, that are written in python and go with the balance gradually shifting to go, talk to each other via [Vulcand](https://github.com/vulcand/vulcand).

**Comment by Analect** [comment]
@horkhe 
Further to your offer to ask follow-on questions ... 

In your forum description of use-cases for kafka-pixy you said:
>The use case that we were shooting for (our use case) is microservice architecture. Where each physical host runs many different applications and some applications may even have several processes running on the same host (e.g. python and nodejs to take advantage of multiple cores). We thought that it would be suboptimal to make all of them connect to Kafka cluster on their own and deal with the complexity of the consumer group management logic. So kafka-pixy was born to deal with that and serve applications with individual messages.

I'm trying to get a better understanding of this and the applicability to my own use-cases, two of which are partly explained below.

1) **job-pipeline, intermediated by kafka**
From your readme, I can see you also have a notion of jobs, but not sure if comparable to mine.
```
{
  "integrations": {
    "pixy_jobs1_62065_2015-09-24T22:21:05Z": [0,1,2,3],
    "pixy_jobs2_18075_2015-09-24T22:21:28Z": [4,5,6],
    "pixy_jobs3_336_2015-09-24T22:21:51Z": [7,8,9]
  },
  "logstash-customer": {
```

As per sequence chart below, let's say I have a series of python scripts (1 through 5), that get run as part of a pipeline or job ... and that each time the job is run, there's a job-instance ID ...and that somehow this job_id and/or instance_id are used to create a topic on kafka, to which subsequent stages in the job subscribe.

![image](https://cloud.githubusercontent.com/assets/4063815/12848264/b6da2292-cc10-11e5-861b-5d8132b65ad7.png)

Am I right in thinking your use-case may be similar, but instead of communicating with the bus directly, these scripts are interfacing to kafka-pixy, which in turn is intermittently messaging back to the bus in batches ... or is kafka-pixy some-how simplifying the creation of a temporary consumer-group on our behalf, such that a series of related scripts utilise this filter? 

![image](https://cloud.githubusercontent.com/assets/4063815/12849218/54e1718e-cc16-11e5-9346-783d3e9c37d7.png)

2) **micro-services in a multi-tenanted environment**
Currently, I'm using a simple set-up on kafka ... using some default consumer group and just two topics "request" and "response" to which all messages from micro-services are produced-to/consumed-from, with pattern-matching happening back on the client, based on a message *type* included as part of the message pay-load.

In a multi-tenanted environment, where perhaps messages from different clients can't be intermingled, it presumably makes sense to partition on the basis of some client_id key ... or does kafka-pixy bring any simplification to this use-case?

I notice you've added an issue yourself vis a vis the new consumerAPI in ver 0.9.  Based on what you've read so far, does that solve part of the problem you were trying to solve with kafka-pixy in terms of offering greater flexibility around consumer groups and being able to add and remove topics from these groups?

Thanks again for entertaining these questions.

**Comment by Analect** [comment]
@horkhe 
Just wondered if you had any thoughts on the above. Thanks v. much.

**Comment by horkhe** [comment]
> Am I right in thinking your use-case may be similar, but instead of communicating with the bus directly, these scripts are interfacing to kafka-pixy, which in turn is intermittently messaging back to the bus in batches ... or is kafka-pixy some-how simplifying the creation of a temporary consumer-group on our behalf, such that a series of related scripts utilise this filter?

No. Our use case is different. I would say that creating topics for each job is not the best fit for Kafka at all, as well as short living user groups. Kafka-Pixy will not help you with the topic life circle management.

> In a multi-tenanted environment, where perhaps messages from different clients can't be intermingled, it presumably makes sense to partition on the basis of some client_id key ... or does kafka-pixy bring any simplification to this use-case?

No simplifications here. And I cannot even think of what that simplification might be.

> I notice you've added an issue yourself vis a vis the new consumerAPI in ver 0.9. Based on what you've read so far, does that solve part of the problem you were trying to solve with kafka-pixy in terms of offering greater flexibility around consumer groups and being able to add and remove topics from these groups?

Support for 0.9 consumer API will not change the way Kafka Pixy operates. From the user perspective the only difference will be that they won't need to specify the ZooKeeper cluster connection string.

**Comment by Analect** [comment]
@horkhe 
Thanks for the response. Had hoped there was a better match!
