### ISSUE TITLE
ClientID is invalid

### ISSUE THREAD

**Issue by Madmess** [mailgun/kafka-pixy#73]
When I try to start pixy the following error occurred with ClientID
I use Kafka 2.10-0.9.0.2
```
[user@m250hdp1 kafka-pixy-v0.11.1-linux-amd64]$ ./kafka-pixy --kafkaPeers "localhost:6667" --zookeeperPeers "localhost:2181" --logging "[{\"name\": \"console\", \"severity\": \"debug\"}]"
Aug 16 18:37:02.205 kafka-pixy INFO PID:20898 [main.go:81:main.main] Starting with config: &{UnixAddr: TCPAddr:0.0.0.0:19092 ClientID:pixy_m250hdp1.inside.corp.int_20898_2016-08-16T18:37:02Z Kafka:{SeedPeers:[localhost:6667]} ZooKeeper:{SeedPeers:[localhost:2181] Chroot:} Producer:{ChannelBufferSize:4096 ShutdownTimeout:30s DeadMessageCh:<nil>} Consumer:{ChannelBufferSize:64 LongPollingTimeout:3s RegistrationTimeout:20s BackOffTimeout:500ms RebalanceDelay:250ms OffsetsCommitInterval:500ms ReturnErrors:false}}
...
Aug 16 18:37:02.207 kafka-pixy INFO PID:20898 [client.go:107:github.com/Shopify/sarama.NewClient] [sarama] Initializing new client
Aug 16 18:37:02.207 kafka-pixy ERROR PID:20898 [main.go:84:main.main] Failed to start service: err=(failed to spawn consumer, err=(failed to create Kafka client for message streams: err=(kafka: invalid configuration (ClientID is invalid))))
```

**Comment by rcoder** [comment]
FWIW I believe this PR fixes this issue: https://github.com/mailgun/kafka-pixy/pull/74

**Comment by slava-vishnyakov** [comment]
Just in case somebody stumbles into this problem before it's fixed - `v0.11.0` doesn't have this problem.

**Comment by horkhe** [comment]
Just curious, is any of you guys using it in production?

**Comment by slava-vishnyakov** [comment]
Not yet, but we are about to :)

**Comment by horkhe** [comment]
@Madmess sorry, my bad, I built the release with `go1.5` and forgot to enable vendoring, as a result incorrect version of `Shopify/sarama` was used. I have rebuilt the Linux archive for `v0.11.1` release, please give it a try. 

@slava-vishnyakov cool, you are probably the very first user outside of Mailgun that I know of. Let me know if you have any issues or feature requests and I will try to address them in timely manner.

**Comment by rcoder** [comment]
We aren't using it in prod yet but we are evaluating it and are likely to do so soon. Expect more inbound PRs as we start hammering on it. :)

**Comment by horkhe** [comment]
@rcoder @slava-vishnyakov we have been using it in production for a quite awhile. Version `v0.11.1` proved to be very stable and has been running for months without reboots. That is why this repo seemed to be neglected, it just works for us.

In our shop all our services talk to Kafka via locally running Kafka-Pixy. Instances consume no more than 50% of CPU and have grown to consume up to 1.7 Gb of virtual memory for our use case. We produce about 500,000,000 messages a day, each probably about 2 Kb in size, and each message is consumed at least 3 times.

I would appreciate if you share your use cases and operational metrics. Anyway have fun playing with it :)

**Comment by slava-vishnyakov** [comment]
@horkhe Excellent, thanks for the heads-up! When we have used it a little in production - I'll be back to share the metrics :)
