### ISSUE TITLE
Unable to receive POST data for Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by cizexzza** [mailgun/kafka-pixy#92]
I send the POST sample is fine for any  Content-Type except "application/x-www-form-urlencoded".

send:
curl -X POST localhost:19092/topics/foo/messages?sync   -H 'Content-Type:text/plain'   -d 'blah blah blah'

Response:
{
  "partition": 0,
  "offset": 41
}

send:
curl -X POST localhost:19092/topics/foo/messages?sync   -H 'Content-Type:application/x-www-form-urlencoded'   -d 'blah blah blah'

Response:
{
  "error": "Message size does not match Content-Length: expected=14, actual=0"
}

How do i receive POST for Content-Type is application/x-www-form-urlencoded?

**Comment by horkhe** [comment]
@cizexzza at the moment only `text/plain` with utf-8 encoding is supported. Why do you need `application/x-www-form-urlencoded` if `text/plain` works fine for you?

**Comment by cizexzza** [comment]
oh, I can not change the data source and the data Content-Type is application/x-www-form-urlencoded .

**Comment by horkhe** [comment]
@cizexzza why you cannot change the content-type? How do you make requests? I mean what programming language+framework are you using?

**Comment by cizexzza** [comment]
i can change my programming language requests  content-type , but i can not change data from other machine equipment , the equipment send data Content-Type is application/x-www-form-urlencoded.

**Comment by horkhe** [comment]
@cizexzza I am just curious what "other machine equipment" you are using that it does not let you these change?

**Comment by cizexzza** [comment]
ya. i just can collect it data.

**Comment by horkhe** [comment]
@cizexzza sorry, I do not understand you.

**Comment by horkhe** [comment]
@cizexzza still interested in this? I can add support for `application/x-www-form-urlencode`.

**Comment by asitm9** [comment]
@horkhe I would be more than happy to add this .

**Comment by horkhe** [comment]
@asitm9 if you want to do that yourself, then please be my guest. By the way, we at Mailgun do not rely on HTTP interface anymore, we use gRPC internally and in fact recommend everybody to do the same.

**Comment by horkhe** [comment]
@cizexzza it should work lick this:
```
